name: Release the font

on:
  push:
    branches:
      - 'master'
    tags:
      - "v*.*"

jobs:
  release-font:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python 3.11 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Compile the font
      run: python main.py
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: OpenDotMatrix.ttf
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}