name: Release the font

on:
  push:
    branches:
      - 'master'

jobs:
  collect-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python 3.11 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Collect stats
      run: python main.py
    - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: OpenDotMatrix.ttf